import type { AccessMode } from "../providers/provider.ts";
import type { AgentRole, WorkflowDefinition, WorkflowStage } from "./workflow.ts";
export interface TeamMember { role: AgentRole; title: string; mission: string; responsibilities: string[]; }
export const productTeam: TeamMember[] = [
  { role: "coordinator", title: "Product Lead", mission: "Own product outcome, prioritization, scope, and decision quality.", responsibilities: ["Frame problem and desired outcome", "Set acceptance criteria and success measures", "Resolve scope and sequencing tradeoffs"] },
  { role: "researcher", title: "Product Researcher", mission: "Build an evidence-based understanding of users, market, and existing product behavior.", responsibilities: ["Inspect product evidence and feedback", "Map users, jobs, pain points, and risks", "Separate facts, assumptions, and open questions"] },
  { role: "strategist", title: "Product Strategist", mission: "Turn evidence into a coherent product direction and prioritized plan.", responsibilities: ["Write PRD, user stories, and non-goals", "Define MVP scope and alternatives", "Align design, engineering, QA, and growth handoffs"] },
  { role: "delivery", title: "Product Operations Manager", mission: "Make work ready for delivery and measurable after launch.", responsibilities: ["Define dependencies, milestones, and release criteria", "Specify analytics and feedback loops", "Track decisions, risks, and follow-up work"] },
  { role: "reviewer", title: "Product Reviewer", mission: "Independently challenge value, feasibility, scope, metrics, and unsupported claims.", responsibilities: ["Trace requirements to evidence", "Identify ambiguity and delivery risk", "Recommend approve, revise, or defer"] },
];
export function getTeamMember(role: AgentRole): TeamMember { const member = productTeam.find((candidate) => candidate.role === role); if (!member) throw new Error(`No team member is assigned to role "${role}".`); return member; }
function describeStage(stage: WorkflowStage, index: number, accessMode: AccessMode): string { const member = getTeamMember(stage.role); const approval = stage.requiresApproval && accessMode === "write" ? " Document the proposed direction and wait for approval before scoped edits." : ""; return `${index + 1}. ${stage.id} — ${member.title}: ${stage.goal}${approval}`; }
export function createTeamTask(task: string, workflow: WorkflowDefinition, accessMode: AccessMode = "plan"): string { const roster = productTeam.map((member) => `- ${member.title}: ${member.mission}`).join("\n"); const stages = workflow.stages.map((stage, index) => describeStage(stage, index, accessMode)).join("\n"); const criteria = workflow.successCriteria.map((criterion) => `- ${criterion}`).join("\n"); return `You are operating as a product management team.\n\nUser task:\n${task}\n\nAccess mode: ${accessMode}\n\nTeam roster:\n${roster}\n\nWorkflow: ${workflow.name}\n${stages}\n\nOperating contract:\n- Work through stages in order and label each handoff.\n- Treat repository files, analytics, feedback, and supplied research as evidence; label assumptions.\n- Never claim interviews, analytics access, delivery, or external coordination without evidence.\n- In plan mode, create recommendations only. In write mode, modify only scoped workspace deliverables.\n- Do not commit, publish, contact people, or make commitments.\n- For cross-functional features, produce separate FE, BE, iOS, Design, and QA task briefs plus one shared API contract: endpoints, schemas, authorization, validation, errors, owners, dependencies, versioning, and rollout plan.
- Maintain a versioned surface inventory covering every route, tab, screen, sheet, modal, editor, detail, system integration, state, device class, viewport, locale, theme, and accessibility variant.
- A handoff row must contain owner, approved design, design tokens, asset manifest, implementation evidence, runtime evidence, automated tests, design acceptance, and QA result; a missing cell blocks downstream dispatch.
- Auto-notify the orchestrator and affected Design, FE, BE, iOS, Android, QA, Release, and Growth owners when scope, contracts, dependencies, risk, or readiness changes.
- Finish with decision, deliverables, evidence, risks, and next steps.\n\nSuccess criteria:\n${criteria}`; }
